Person_infoboxes = ['person',
                    'academic',
                    'architect',
                    'artist',
                    'astronaut',
                    'aviator',
                    'adult biography',
                    'chef',
                    'college coach',
                    'Chinese-language singer and actor',
                    'Christian leader',
                    'classical composer',
                    'clergy',
                    'comedian',
                    'comics creator',
                    'criminal',
                    'dancer',
                    'economist',
                    'engineer',
                    'fashion designer',
                    'go player',
                    'Hindu leader',
                    'Jewish leader',
                    'Latter Day Saint biography',
                    'Magic: The Gathering player',
                    'martyrs',
                    'medical person',
                    'member of the Knesset',
                    'military person',
                    'leader',
                    'model',
                    'musical artist',
                    'Muslim leader',
                    'Native American leader',
                    'officeholder',
                    'pageant titleholder',
                    'philosopher',
                    'pirate',
                    'Playboy Playmate',
                    'playwright',
                    'poker player',
                    'police officer',
                    'presentor',
                    'eSports player',
                    'snooker player'
                    'saint',
                    'scientist',
                    'spy',
                    'theologian',
                    'War on Terror detainee',
                    'writer',
                    'Youtube personality',
                    'civil servant',
                    'AM',
                    'Canadian PM',
                    'Canadian senator',
                    'candidate',
                    'chancellor',
                    'congressional candidate',
                    'congressman',
                    'defence minister',
                    'deputy first minister',
                    'deputy prime minister',
                    'doge',
                    'Eritrea cabinet official',
                    'first lady',
                    'first minister',
                    'governor',
                    'governer-elect',
                    'governor general',
                    'governor-general',
                    'Indian politician',
                    'judge',
                    'lt governor',
                    'mayor',
                    'MEP',
                    'minister',
                    'MLA',
                    'MP',
                    'MSP',
                    'PM',
                    'politician',
                    'premier',
                    'president',
                    'president-elect',
                    'prime minister',
                    'prime minister-elect',
                    'representative-elect',
                    'SCC chief justice',
                    'SCC puisne justice',
                    'secretary-general',
                    'senator',
                    'senator-elect',
                    'speaker',
                    'state representative',
                    'state SC associate justice',
                    'state SC justice',
                    'state senator',
                    'US ambassador',
                    'US associate justice',
                    'US cabinet official',
                    'US chief justice',
                    'US territorial governor',
                    'vice president',
                    'sportsperson',
                    'Motocross rider',
                    'motorcycle rider',
                    'speedway rider',
                    'F1 driver',
                    'Champ Car driver',
                    'NASCAR driver',
                    'Le Mans driver',
                    'racing driver',
                    'WRC driver',
                    'speed skater',
                    'badminton player',
                    'baseball biography',
                    'basketball biography',
                    'biathlete',
                    'bodybuilder',
                    'boxer', 
                    'boxer (amateur)',
                    'chess biography',
                    'cricketer',
                    'curler',
                    'cyclist',
                    'darts player',
                    'fencer',
                    'equestrian',
                    'figure skater',
                    'football biography',
                    'football official',
                    'golfer',
                    'gymnast',
                    'field hockey player',
                    'ice hockey player',
                    'GAA player',
                    'handball biography',
                    'horseracing personality',
                    'lacrosse player',
                    'martial artist',
                    'NFL biography',
                    'professional wrestler',
                    'sumo wrestler',
                    'sailor',
                    'surfer',
                    'snooker player',
                    'sport wrestler',
                    'squash player',
                    'swimmer',
                    'table tennis player',
                    'tennis biography',
                    'volleyball biography',
                    'rugby biography',
                    'rugby league biography',
                    'amateur wrestler',
                    'noble',
                    'royalty',
                    'religious biography',
                    'Egyptian dignitary',
                    'peer',
                    'pharoh',
                    'college football player',
                    'CFL biography',
                    'climber',
                    'AFL biography',
                    'alpine ski racer',
                    'NCAA athlete',
                    'netball biography',
                    'skier']

Location_infoboxes = ['amusement park',
                       'ancient site',
                       'Egyptian tomb',
                       'historic site',
                       'World Heritage Site',
                       'NRHP',
                       'canal',
                       'body of water',
                       'beach',
                       'cave',
                       'cemetry',
                       'country',
                       'ecoregion',
                       'geopolitical organization',
                       'former country',
                       'former subdivision',
                       'glacier',
                       'cycling path',
                       'forest',
                       'hiking trail',
                       'islands',
                       'Scottish island',
                       'mountain',
                       'river',
                       'waterfall',
                       'valley',
                       'spring',
                       'park',
                       'protected area',
                       'port',
                       'power station',
                       'settlement',
                       'water park',
                       'zoo',
                       'building',
                       'airport',
                       'casino',
                       'convention center',
                       'factory',
                       'hotel',
                       'hut',                       
                       'library',
                       'lighthouse',
                       'mine',
                       'monument',
                       'museum',
                       'observatory',
                       'oil refinery',
                       'prison',
                       'religious building',
                       'church',
                       'Hindu temple',
                       'Monastery',
                       'restaurant',
                       'shopping mall',
                       'station',
                       'venue',
                       'swimming venue',
                       'motorsport venue',
                       'cricket ground',
                       'golf facility',
                       'windmill',
                       'bridge',
                       'dam',
                       'military memorial',
                       'tunnel',
                       'road',
                       'highway',
                       'street',
                       'Australian place',
                       'New Zealand suburbs',
                       'Russian district',
                       'Belgium Municipality',
                       'city Japan',
                       'Finnish municipality',
                       'French commune',
                       'German location',
                       'Greek Dimos',
                       'Hungarian settlement',
                       'India district',
                       'Israel Municipality',
                       'Italian comune',
                       'Korean settlement',
                       'Palestine municipality',
                       'Partido Argentina',
                       'South African town',
                       'Swiss town',
                       'UK place',
                       'U.S. county']

Organization_infoboxes = ['bus company',
                          'airline',
                          'central bank',
                          'exchange',
                          'record label',
                          'organization',
                          'government agency',
                          'political party',
                          'American_State_Political_Party',
                          'Indian political party',
                          'political youth organization',
                          'law enforcement agency',
                          'fire department',
                          'space agency',
                          'military unit',
                          'national military',
                          'legislature',
                          'institute',
                          'laboratory',
                          'observatory',
                          'school',
                          'university',
                          'hospital',
                          'brewery',
                          'winery',
                          'journal',
                          'magzine',
                          'publisher',
                          'newspaper',
                          'company',
                          'law firm',
                          'union',
                          'sports team',
                          'American Football Team',
                          'NFL team',
                          'football club',
                          'national football team',
                          'baseball team',
                          'basketball club',
                          'national basketball team',
                          'national cricket team',
                          'cricket team',
                          'cycling team',
                          'national handball team',
                          'national hockey team',
                          'hockey team',
                          'Pro hockey team',
                          'F1 team',
                          'motor racing team',
                          'NASCAR team',
                          'rugby league club',
                          'rugby team',
                          'radio station',
                          'broadcast',
                          'brand',
                          'residential college',
                          'UK school',
                          'militant organization',
                          'architectural practice',
                          'criminal organization',
                          'sport governing body',
                          'tennis cup team',
                          'volleyball club',
                          'national volleyball team',
                          'national water polo team',
                          'wrestling team',
                          'ballet company',
                          'choir',
                          'orchestra',
                          'theatre group',
                          'Christian church body',
                          'religious group',
                          'high court',
                          'family',
                          'league',
                          'football league',
                          'musical group or band']